'''
The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
'''

from math import sqrt

start = int(1e1)
end = int(1e10)
max_divs = 0

tri_num = sum(x for x in range(1, start))

for n in range(start, end):
	tri_num = tri_num + n
	if tri_num % 1 == 0:
		#check divisors
		divs = 2
		for div in range(2, int(tri_num/2)):
			if tri_num % div == 0:
				divs = divs + 1
		# update max divisors
		if divs > max_divs:
			max_divs = divs
		if divs > 500:
			print(tri_num, divs)
			break
		if n % 100 == 0: print(n, tri_num, max_divs)
input()