#/usr/bin/env
# 0002b - Even Fibonacci numbers.py

'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the the_sum of the even-valued terms.
'''

def fib(cieling):
    a, b = 1, 1
    while b < cieling:
        yield b
        a, b = b, a+b

def main():
    print( sum( [n for n in fib(4e6+1) if n % 2 == 0] ) )
    # print(len([n for n in fib(4e6+1)]))

if __name__ == '__main__':
    import os, sys
    main()
