'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the the_sum of the even-valued terms.
'''

def Fibonacci_sum_even(max, the_sum, a, b):
	if b > max:
		print(the_sum)
		return the_sum
	if b % 2 == 0:
		the_sum = the_sum + b
	c = a + b
	Fibonacci_sum_even(max, the_sum, a=b, b=c)

Fibonacci_sum_even(max=4e6+1, the_sum=0, a=1, b=2)